// УЖЕ НЕ ИСПОЛЬЗУЕТСЯ
export interface IWorks {
  link: string;
  title: string;
  id?: string;
  image: string;
  text: string;
  tag: string;
  year: string;
}

export const WORKS_ENUM: IWorks[] = [
  {
    link: "works/01",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
  {
    link: "about",
    title: "About",
    id: "01",
    image: "/example.png",
    text: "Lorem ipsum dolor sit",
    tag: "Web Design",
    year: "2024",
  },
];
